### PR TITLE
Changes to elastic scattering generator to allow spectrum to be set from macro

### PR DESCRIPTION
**Pull request by ekneale**
Updates to ESgen and ESgenMessenger; new example macro.

### CODE REVIEW

**Review by stw4198 — DISMISSED** [review]

**Comment by stw4198** [comment]
I've tested these changes and they work as expected (see attached images)

CNO_10K_water_macro
[CNO_KE.pdf](https://github.com/AIT-WATCHMAN/rat-pac/files/4858875/CNO_KE.pdf)

**Comment by MorganAskins** [comment]
Should we include a parameter to specify neutrino charge and flavor? Looks like this was written for anti-neutrinos
image

**Comment by MorganAskins** [comment]
Especially for solar neutrino studies, the other flavors should be included
image

**Comment by stw4198** [comment]
I think including other flavours would be useful. I have had an issue where the error 

Spectrum lookup failure
IBD[].emin not found

 arises when using the latest rat-pac with the changes to the elastic scattering included. I haven't yet worked out the source as the ES generator should be pulling a spectrum from SPECTRUM.RATDB, which it did in a previous rat-pac version, so shouldn't need a minimum value for IBD energy

**Comment by ekneale** [comment]
Good point @MorganAskins.  The es generator in the public rat-pac already has this modification, so perhaps it would be better to test that out and bring it into the AIT-WATCHMAN rat at this point if we are happy with it?

**Comment by MorganAskins** [comment]
@ekneale What the plan with this PR? Is the plan to update this with changes similar to the public rat-pac es generator, or are we going to just kill this PR and replace with a full swap from there?

**Comment by ekneale** [comment]
It makes most sense to replace with a full swap from the public rat es generator. This latest change was a temporary fix to allow @dazeley2 to generate es events for reactor antineutrinos at Boulby. However, @dazeley2 has found an issue with the costheta from this generator and so I think we should go for the full swap now. It can't be a straight swap, however, since we currently only have access to integration spectra.

**Comment by MorganAskins** [comment]
Ok I have labeled as "on hold" then. Feel free to delete this PR whenever you're ready.

**Comment by ekneale** [comment]
Will do. I'll leave it for the moment as Steven has been using it. Currently working on the full swap.

**Pull request closed without merging**
