### PR TITLE
Reactor IBD Messenger

### PR DESCRIPTION
**Pull request by MorganAskins**
- New messenger for the IBD generator
- IBD generator now loads ratdb tables by index, allowing
  for multiple IBD.ratdb entries (corresponding to different
  spectra / detector locations).
- IBDgenMessenger tells IBDgen which index to use, defaults to the
  original Vogel spectrum (so backwards compatible)
- geoneutrino2ratdb.py converts csv files from geoneutrino.org into
  ratdb entries which can be added to IBD.ratdb
- Used the tool to generate spectra for boulby, separating the
  hartlepool cores, geoneutrinos, and world reactors.

### CODE REVIEW

**Comment by MorganAskins** [comment]
Can be used in a macro:
```
/generator/add combo ibd:regexfill:poisson
/generator/ibd/spectrum boulby_geo
/generator/vtx/set IBD 1 0 0
/generator/pos/set detector+
```
The only new line is the second one, and if it's left out then it defaults to the old behaviour
(which is now reading the ratdb entry for name: IBD, index: "default")

**Comment by MorganAskins** [comment]
So the spectra used before in SPECTRUM.ratdb are used for the VertexGen_Spectrum generator which is not specific to IBD and can be any particle. The IBD generator already loads in IBD.ratdb tables so this maintains backwards compatibility.

**Comment by MorganAskins** [comment]
Added the ability to toggle on/off the neutrons and/or positrons. Also an example macro.

**Comment by ekneale** [comment]
Ran with positron and neutron on:

    CountProc: Event 990 (636 triggered events)
    CountProc: Event 1000 (642 triggered events)
    Run time:   3405.15 sec
    CPU usage: user  3335.33 sec	sys   1.84 sec 
    Processor usage statistics
    --------------------------
             Event source: 3.223 sec/event
            lesssimpledaq: 0.000 sec/event
                    count: 0.000 sec/event
                  outroot: 0.002 sec/event
    --------------------------
    Total: 3.225 sec/event

    CountProc: Total # of events 1000 (642 triggered events)


642 triggered events with new generator, compared with 614 triggered events with old generator using the same small_hartlepool spectrum. Old generator seems to run more quickly:

     CountProc: Event 990 (605 triggered events)
     CountProc: Event 1000 (614 triggered events)
     Run time:   1478.23 sec
     CPU usage: user  1474.02 sec	sys   1.60 sec
     Processor usage statistics
     --------------------------
             Event source: 1.364 sec/event
            lesssimpledaq: 0.000 sec/event
                    count: 0.000 sec/event
                  outroot: 0.002 sec/event
     --------------------------
     Total: 1.366 sec/event

     CountProc: Total # of events 1000 (614 triggered events)

I will check this and then try to generate neutrons/positrons only next.

**Comment by MorganAskins** [comment]
Oh that speed difference is very interesting (definitely requires looking into). I would hope they would be statistically similar, but run in nearly the same amount of time since the underlying sampling is supposed to be the same, maybe it's getting stuck somewhere weird.

**Comment by ekneale** [comment]
Ran again to double-check and the times are more in line with each other this time. 
New generator:

    CountProc: Event 480 (277 triggered events)
    CountProc: Event 490 (284 triggered events)
    CountProc: Event 500 (292 triggered events)
    Run time:   1962.66 sec
    CPU usage: user  1960.29 sec	sys   1.31 sec
     Processor usage statistics
    --------------------------
             Event source: 3.730 sec/event
            lesssimpledaq: 0.000 sec/event
                    count: 0.000 sec/event
                  outroot: 0.003 sec/event
    --------------------------
    Total: 3.733 sec/event

    CountProc: Total # of events 500 (292 triggered events)

Old generator with small_hartlepool spectrum

    CountProc: Event 500 (292 triggered events)
    Run time:   1952.87 sec
     CPU usage: user  1950.73 sec	sys   1.25 sec
     Processor usage statistics
     --------------------------
             Event source: 3.711 sec/event
            lesssimpledaq: 0.000 sec/event
                    count: 0.000 sec/event
                  outroot: 0.003 sec/event
     --------------------------
    Total: 3.713 sec/event

    CountProc: Total # of events 500 (292 triggered events)

**Comment by ekneale** [comment]
Simulated 100 positrons using the new generator with neutrons off. Timing and energy look sensible:

positrons_only

positrons_only_KE


and 100 neutrons with positrons off:

neutrons_only

neutrons_only_KE

**Pull request merged**
