### PR TITLE
Added WLS functionality via flag in PMT field

### PR DESCRIPTION
**Pull request by MullenAustin**
WLS plates are now added to the detector via a flag in the "inner_pmts" field, in the same manner that light cones are implemented.  You specify the wls plate size, inner radius, material, and reflector material in the geo file, as seen in Watchman.geo.

### CODE REVIEW

**Comment by gsmith23** [comment]
added WLS flag functionality
f68114b

Line 484 - 485 
"black_sheet_side” dimensions – changed from 6710, 6700 to 6770, 6760 – require dimensions check from someone more familiar with geomatry

Line 698 – 702
Plate appears to be ½ inch thick and a 24.5 cm wide square

Line 700
wls_radius: [116.0,96.0] – what is this?

ref_surface: "nonreflective_tarp" appears to specify glisur model but uses unified model coefficiencts. This surface appears to have zero reflectivity. Was this as intended? Unity reflectivity specified below

Merge remote-tracking branch 'upstream/master' …
1f4c2ab

No changes would to apply upstream/master from this commit.

removed unnecessary line from previous commit
bac044a

I agree that this header file was not needed.

changed the watchman geo file to default to no wls plates
1af2434

Agree that defaulting to no wls plate is best

fixed issue with wls reflector
21db7b8

Change to reflective tarp seems better than nonreflective.  Does this apply to all outer plate surfaces?

As above - ref_surface: "reflective_tarp" appears to specify glisur model but uses unified model coefficiencts. This surface appears to have 100% reflectivity which seems an overestimation.

fixed crash on build
fcb0341

Code is same as on upstream/master branch

added wls_offset variable for plate placement on PMT

wls_plates flag now set to 1 – does this default to include wls plate again now?
wls_radius: [127.0,108.0] – what is this and why 19?
wls_offset: 30.0 – places 30 mm from PMT centre?

Line 177 – 179 – tidy line order unless this it is deliberate – line 176 sets default material and corresponding try is not until line 180

**Review by gsmith23 — APPROVED** [review]
These changes look good and should be made available for wider testing before use in production runs.

**Comment by MarcFBergevin** [comment]
A small request before approving the merge. Austin, could you pull in your PR the new detector configuration
Screen Shot 2021-02-26 at 08 44 24

Right now it is giving me the following error message:
```G4Material::GetMaterial() WARNING: The material: doped_water does not exist in the table. Return NULL pointer.
G4Material::GetMaterial() WARNING: The material: doped_water does not exist in the table. Return NULL pointer.
G4Material::GetMaterial() WARNING: The material: doped_water does not exist in the table. Return NULL pointer.
G4Material::GetMaterial() WARNING: The material: doped_water does not exist in the table. Return NULL pointer.
GeoPMTArrayFactory: Constructing volume inner_pmts
DB: Field GEO[inner_pmts].wls_plates lookup failure.  Does not exist or has wrong type.
```

**Comment by MullenAustin** [comment]
I have updated the code so that:
1) there is now a wls_plates flag (set to 0) present in the trade study geometries geo files
2) it no longer requires a wls_plates field to run.  If no wls_plates variable is provided, it defaults to 0.

**Comment by MarcFBergevin** [comment]
This PR is a bit old. Austin, does this PR include your recent work presented in the last collaboration meeting?

**Comment by MullenAustin** [comment]
Hey Marc, I didn't realize this PR was still open....  It looks like it automatically keeps it up to date with my branch -- the branch is up to date with my new optical properties, but I'm still testing some stuff out and cleaning things up, so it's not necessarily ready to merge.  If you want you can close this old PR and I can open a new one soon (probably next week) with all of the new optical properties.  Or we can keep this PR open and I'll go through and clean up my current branch and get it into a PR-worth status next week.

**Comment by MarcFBergevin** [comment]
Might be a bit simpler to close this branch and reopen since it has been a while and the code has changed a bit. If there is any issues we can reopen it without much issues. Let me close this PR for now.

**Comment by MarcFBergevin** [comment]
Closing PR.

**Pull request closed without merging**
