### PR TITLE
NoiseProc addition

### PR DESCRIPTION
**Pull request by MorganAskins**
Moving PMT noise to its own processor which modifies the MCPMT of
each event. Noise still exists in GSim, but this is triggered
separately through NOISEProc.ratdb.

Still needs a few things:
1. PMT Time and Charge Models
2. Prune old noise hits so we do not stack them.

### CODE REVIEW

**Comment by MarcFBergevin** [comment]
It may be a bad test, but it did seem that the event processing rate went up by 20%. May be due to how the test was performed.

**Comment by MorganAskins** [comment]
- Added SetNumDark in noise proc so that GetNumDark returns the number of dark hits in the MC branch.
- Flag in ratdb to only generate noise near real hits, currently +- max(lookback, lookforward), default is 1 us around real hits.

Example in macro
```
/rat/proc noise
/rat/procset rate 3000.0
/rat/procset nearhits 1
```

Default is actually 1, so IBD would NOT have noise hits sitting between the e+ and n unless this flag is set to on. Also, in either case lesssimpledaq will produce excess triggers since it's not designed to handle noise.

**Comment by ekneale** [comment]
Ran a few tests. The noise processor had to be called before the daq in the macro for the noise hits to be assigned as dark hits AND read as dark hits in the daq. Using the following macro:

    /glg4debug/glg4param omit_muon_processes  0.0
    /glg4debug/glg4param omit_hadronic_processes  0.0
    
    /rat/db/set DETECTOR experiment "Watchman"
    /rat/db/set DETECTOR geo_file "Watchman/Watchman.geo"
    
    /run/initialize
    
    # BEGIN EVENT LOOP
    /rat/proc noise
    /rat/procset rate 8000.0
    /rat/procset nearhits 1
    /rat/proc lesssimpledaq
    /rat/proc count
    /rat/procset update 1
    /rat/proclast outroot
    #END EVENT LOOP

Assigns isDarkHit boolean as shown by daq output (final column):

    (time,charge,id, dark hit): (-19.9614,1.37802,943,1)
    (time,charge,id, dark hit): (-13.0953,1.08074,3018,1)
    (time,charge,id, dark hit): (24.4128,0.611922,3273,0)
    (time,charge,id, dark hit): (50.1397,0.554749,3313,0)
    (time,charge,id, dark hit): (55.9146,1.32409,3279,0)
    (time,charge,id, dark hit): (68.5888,1.0273,1353,1)
    (time,charge,id, dark hit): (101.093,1.46943,3312,0)
    (time,charge,id, dark hit): (104.959,1.45531,1187,1)
    (time,charge,id, dark hit): (120.826,0.788575,3279,0)
    (time,charge,id, dark hit): (121.627,0.955966,2916,1)
    (time,charge,id, dark hit): (127.399,1.18681,3438,0)

isDarkHit information used in daq to trigger off 'real' hits only and number of triggers remained within expected statistical fluctuation: 336 triggered positron events of 1000 (8kHz) and 339 triggered positron events out of 1000 (3kHz) with a 6-hit trigger threshold.

Dark hit information now saved correctly (3kHz noise in red, 8kHz noise in blue):

numDarkHits

Nhits information looks sensible for 3kHz noise (top) and 8kHz noise (bottom):

Nhits_3kHz

Nhits_8kHz

However I don't think we have an equivalent of GetNumDark to give the total number of hits (rather than the total number of PMTs hit) to double check the numbers.

Using /rat/procset nearhits 1 and /rat/procset nearhits 0, looks like dark hits are generated in a window from 1us before the first real hit to 1us after the last real hit. Need to test with IBD events.

**Comment by MorganAskins** [comment]
Included an example macro and updated the branch to match master

**Pull request merged**
