### PR TITLE
LessSimpleDaq trigger

### PR DESCRIPTION
**Pull request by ekneale**
First implementation of 6-hit trigger in LessSimpleDAQProc.

Work in progress.

### CODE REVIEW

**Comment by MarcFBergevin** [comment]
This seems to fix some of the retrigger issues:

https://files.slack.com/files-pri/TCY2F1X19-F0192GPLLGG/image.png

**Comment by MarcFBergevin** [comment]
I have confirmed that the remaining lower energy peak is from events in the veto.

**Comment by ekneale** [comment]
Removed for now the option to trigger on dark noise hits or just 'real' hits - splitevDAQ has this option so I opted to keep LessSimpleDAQ as simple as possible. It can however be easily reinstated.

@MarcFBergevin should I at this stage also add the photon source as an output?

**Comment by MorganAskins** [comment]
Looks to be working from my end as well.

**Review by MorganAskins — APPROVED** [review]

**Pull request merged**
