### PR TITLE
Bug fix 231Th infinite loop

### PR DESCRIPTION
**Pull request by davehadley**
There appears to be a typo in the `beta_decays.dat`. This code that parses this file gets stuck in an infinite loop when trying to parse the beta decay table for 231Th.

This pull request consists of two changes:

(1) "Fixed" the typo. I think that @ekneale made the most recent commit to the affected line in the dat file. Can you confirm if this change is correct?

(2) I have modified `BetaFunction.cc` to throw a fatal exception with an appropriate error message rather than get stuck in an infinite loop.

### CODE REVIEW

**Comment by davehadley** [comment]
I spoke with @ekneale in the UK simulations meeting this morning. She pointed out that there is already a pull request in place for this: #137. Sorry about that. I didn't spot it when I submitted #140.

Comparing d42bf33 (@davehadley commit) with 272c7b6 (@ekneale commit), I see that my guess at the correct fix was incorrect. I have merged @ekneale's changes from #137 into this pull request #140.

I suggest that the package maintainers should either:

(1) Merge #137 (fix to dat file). I can then rebase #140 on master and only include commit a4b7121 and 7fce3e2 (throws exception rather than get stuck infinite loop to protect against a similar bug being introduced in future).

(2) You can just merge #140 as it now includes the changes in #137.

**Comment by MarcFBergevin** [comment]
I have tried to compile this and I am getting the following error:

```Scanning dependencies of target RATDict
/usr/WS2/bergevin/WMUtils/rat-pac_pr140/src/gen/src/BetaFunction.cc:9:10: fatal error: G4Exception.hh: No such file or directory
 #include <G4Exception.hh>
          ^~~~~~~~~~~~~~~~
compilation terminated.
gmake[3]: *** [src/gen/CMakeFiles/gen.dir/build.make:89: src/gen/CMakeFiles/gen.dir/src/BetaFunction.cc.o] Error 1
gmake[3]: Leaving directory '/usr/WS2/bergevin/WMUtils/rat-pac_pr140/build'
gmake[2]: *** [CMakeFiles/Makefile2:664: src/gen/CMakeFiles/gen.dir/all] Error 2```

**Comment by davehadley** [comment]
Sorry. I have been compiling with the most recent version of GEANT4 (10.6).
Apparently this header was only introduced in 10.5.
I guess that you are using 10.4 or earlier?
It looks like in earlier versions this existed in the header:
`./source/global/management/include/globals.hh`

I will fix this pull request so that it is compatible with 10.4.

**Review by MarcFBergevin — APPROVED** [review]
Was able to compile code and run example macro with no issues. 

Code provided following with new data/beta_decay.dat
```CountProc: Event 2200 (0 triggered events)
CountProc: Event 2400 (0 triggered events)
Run time:    116.82 sec
CPU usage: user    56.01 sec    sys   1.52 sec
Processor usage statistics
--------------------------
             Event source: 0.001 sec/event
            lesssimpledaq: 0.000 sec/event
              fitcentroid: 0.000 sec/event
                  fitpath: 0.000 sec/event
                    count: 0.000 sec/event
                  outroot: 0.000 sec/event
--------------------------
Total: 0.001 sec/event

CountProc: Total # of events 2500 (0 triggered events)
=======================================================================
======       Pre-compound/De-excitation Physics Parameters     ========
=======================================================================
Type of pre-compound inverse x-section              3
Pre-compound model active                           1
Pre-compound low energy (MeV)                       0.1
Type of de-excitation inverse x-section             3
Type of de-excitation factory                       Evaporation
Number of de-excitation channels                    8
Min excitation energy (keV)                         0.01
Min energy per nucleon for multifragmentation (MeV) 1e+05
Level density (1/MeV)                               0.1
Time limit for long lived isomeres (ns)             1442.7
Internal e- conversion flag                         1
Store e- internal conversion data                   1
Electron internal conversion ID                     0
Correlated gamma emission flag                      0
Max 2J for sampling of angular correlations         10
=======================================================================
Graphics systems deleted.
Visualization Manager deleting...
WARNING - Attempt to delete the solid store while geometry closed !
WARNING - Attempt to delete the logical volume store while geometry closed !
WARNING - Attempt to delete the physical volume store while geometry closed !
WARNING - Attempt to delete the region store while geometry closed !
```

With old data/beta_decay.dat
```
      issued by : /usr/WS2/bergevin/WMUtils/rat-pac_pr140/src/gen/src/BetaFunction.cc
failed to parse 231Th in /usr/WS2/bergevin/WMUtils/rat-pac_pr140/data/beta_decays.dat
*** Fatal Exception *** core dump ***
```

This seems to work as intended.

**Pull request merged**
